version: "3"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: flagr
      MYSQL_ROOT_PASSWORD: password
  flagr:
    image: heycar/flagr:0.2.9
    depends_on:
      - database
    ports:
      - "7000:7000"
    environment:
      FLAGR_DB_DBDRIVER: mysql
      FLAGR_DB_DBCONNECTIONSTR: "root:password@tcp(database:3306)/flagr?parseTime=true"
    command: > 
      bash -c "sleep 5 && ./flagr"
